language: python
python:
    - "3.8"
# command to install dependencies
install:
    - pip install flask
    - pip install flask_restful
    - pip install mysql.connector
script:
    - python -m unittest tests/test_service.py
    - python -m unittest tests/test_rest.py